#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_get tg-sendmail/bot-token

token="$RET"
sed -i "s/bot_token: .*/bot_token: \"${token}\"/" /etc/tg-sendmail.yaml

db_get tg-sendmail/chat-id

chat_id="$RET"
sed -i "s/chat_id: .*/chat_id: \"${chat_id}\"/" /etc/tg-sendmail.yaml

touch /var/log/tg-sendmail.log
chmod 666 /var/log/tg-sendmail.log

sed -i "s%path: .*%path: /var/log/tg-sendmail.log%" /etc/tg-sendmail.yaml

exit 0
