name: Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install dev deps
        run: sudo apt install devscripts debhelper dh-exec dh-make dh-python
      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build package
        run: debuild --no-lintian
