name: Builder

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install dev deps
        run: sudo apt install devscripts dh-exec dh-make dh-python
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build package
        run: debuild
